spring.application.name=HumanResourceApplicationFrontend
server.port=8085
backend.api.url=http://172.16.160.115:8080
server.address=0.0.0.0

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false

